@growers_market.Server_HostAddress = http://localhost:5260

### Register Account
POST {{growers_market.Server_HostAddress}}/api/account/register
Content-Type: application/json
{
  "username": "lkcina",
  "email": "lkcina6@gmail.com",
  "password": "P@ssword1234"
}


### User Login
POST {{growers_market.Server_HostAddress}}/api/account/login
Content-Type: application/json
{
  "username": "lkcina",
  "password": "P@ssword1234"
}

### Get All Species
GET {{growers_market.Server_HostAddress}}/api/species
Accept: application/json

### Get Species By Id
GET {{growers_market.Server_HostAddress}}/api/species/10
Accept: application/json

### Get All Species From Perenual
GET {{growers_market.Server_HostAddress}}/api/species/perenual?Q=rose
Accept: application/json

### Get Direct from Perenual
GET https://perenual.com/api/species/details/3?key=sk-uDos677eca3f7332f8182&indoor=1